version: '{build}'
clone_depth: 50
install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET GECKODRIVER=C:\Tools\WebDriver
  - SET CHROMEDRIVER=C:\Tools\WebDriver\chromedriver.exe
  - SET PATH=%JAVA_HOME%\bin;%GECKODRIVER%;%CHROMEDRIVER%;%PATH%
#  - echo PATH %PATH%
#  - echo JAVA_HOME %JAVA_HOME%
  - java -version
#  - javac -version
  - mvn -version
build: off

environment:
  global:
    MAVEN_OPTS: "-Xmx2048M"

before_test:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
- ps: Set-ScreenResolution 1280 768

test_script:
- ps: |
    mvn test -P appveyor --batch-mode

on_finish:
- ps: |
    (new-object System.Net.WebClient).UploadFile(
      "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID",
      (Resolve-Path .\junit-results.xml)
    )

deploy: off

artifacts:
  - path: instanceManagerSequence.txt

cache:
  - C:\Users\appveyor\.m2 -> pom.xml
