version: '{build}'
clone_depth: 50
install:
#  - echo JAVA_HOME %JAVA_HOME%
  - choco install ant --limit-output --ignore-dependencies
#  - echo JAVA_HOME %JAVA_HOME%
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%JAVA_HOME%\bin;%PATH%
#  - echo PATH %PATH%
#  - echo JAVA_HOME %JAVA_HOME%
#  - echo ANT_HOME %ANT_HOME%
  - java -version
#  - javac -version
  - ant -version
build: off

# note that PowerShell scripts need an empty line between each command
# this is not normal for PowerShell and is likely a side effect of
# AppVeyor's YAML processing
test_script:
- ps: >-
    ant checkPropertiesFiles appveyor-ci-test

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\junit-results.xml))

deploy: off
