version: '{build}'
clone_depth: 50
install:
  - choco install ant --limit-output
#  - echo JAVA_HOME %JAVA_HOME%
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
#  - echo PATH %PATH%
#  - echo JAVA_HOME %JAVA_HOME%
#  - echo ANT_HOME %ANT_HOME%
  - java -version
#  - javac -version
  - ant -version
build: off
test_script:
#- cmd: >-
#    ant ci-test
  - ps: >-
    ant appveyor-ci-test
    
    $wc = New-Object 'System.Net.WebClient'
    
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit-results.xml))
deploy: off
